---
default:
    - debug: true
      open: public/ta_showclip.swf
      extra: -use-network=false
    
library-path:
    - source/swc

source-path:
    - source/classes
    - ../../trunk/source
    
applications:
    - class: source/classes/ta_showclip.as
      output: public/ta_showclip.swf
      
    # - class: source/classes/AAShip.as
    #   output: public/AAShip.swf
      