# ---
# default:
#     - debug: false
#       extra: -use-network=false
# 
# source-path:
#     - source/classes
#     
# applications:
#     - class: source/classes/minimalcomps.as
#       output: source/swc/minimalcomps.swc
---
default:
    - debug: false
      open: public/textanim_maker.swf
      extra: -use-network=false
    
library-path:
    - source/swc

source-path:
    - source/classes
    - ../branches/linked/source
    
applications:
    - class: source/classes/textanim_maker.as
      output: public/textanim_maker.swf