---
default:
    - debug: false
      open: lib/textanim.swf
      extra: -use-network=false

source-path:
    - source
    - lib
    
applications:
    - class: lib/textanim.as
      output: lib/textanim.swc
      
asdoc:
    - title: "TextAnim Documentation"
      footer: "(c) Copyright 2009 - MIT LICENSE. All Rights Reserved. http://code.google.com/p/textanim"
      output: doc
      exclude-dirs:
          - lib
      source-path:
          - source